spring.application.name=retail-banking-system

# ? "spring.datasource.url" hona chahiye, na ki "spring.database.url"
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/banking_system

spring.datasource.username=root
spring.datasource.password=sami123

# ? "spring.jpa.properties.hibernate.dialect" hona chahiye, na ki "spring.java.properties.hibernate.dialect"
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
